#!/usr/bin/env ruby

require 'rubygems'

require File.dirname(__FILE__) + '/lib/pelvis'

require File.dirname(__FILE__) + '/examples/actors/herault'
require File.dirname(__FILE__) + '/examples/actors/randomz'
require File.dirname(__FILE__) + '/examples/actors/chained'
require File.dirname(__FILE__) + '/examples/actors/inner'

module Logging
  def receive(data)
    log "Received data: #{data.inspect}"
  end

  def complete(event)
    log "Completed with #{event.inspect}"
  end

  def log(message)
    puts "%0.7f: %s" % [Time.now.to_f, message]
  end
end

def connect_herault
  Pelvis.connect(:local, {:identity => "herault"}, [Herault]) do |agent|
    puts "herault is ready"
    connect_foo
  end
end

def connect_foo
  Pelvis.connect(:local, {:identity => "foo"}, [Randomz]) do |agent|
    puts "foo is ready"
    connect_bar
  end
end

def connect_bar
  Pelvis.connect(:local, {:identity => "bar"}) do |agent|
    puts "bar is ready"
    agent.request(:all, "/do/random", {}, :callback => Logging)
  end
end

EM.run do
  connect_herault
end
