#!/usr/bin/env ruby

require 'rubygems'

require File.dirname(__FILE__) + '/lib/pelvis'

require File.dirname(__FILE__) + '/examples/actors/herault'
require File.dirname(__FILE__) + '/examples/actors/randomz'
require File.dirname(__FILE__) + '/examples/actors/chained'
require File.dirname(__FILE__) + '/examples/actors/inner'

module Logging
  def receive(data)
    log "Received data: #{data.inspect}"
  end

  def complete(event)
    log "Completed with #{event.inspect}"
  end

  def log(message)
    puts "%0.7f: %s" % [Time.now.to_f, message]
  end
end

Pelvis::Router.start do |router|
  herault = router.agent("herault", [Herault])
  foo = router.agent("foo", [])
  bar = router.agent("bar", [Chained])
  baz = router.agent("baz", [Inner])

  foo.request("/chained", {}, :callback => Logging) #, :identities => ["bar"])

  #console(bar)
end
