#!/usr/bin/env ruby

require 'rubygems'

require File.dirname(__FILE__) + '/lib/pelvis'
require 'pelvis/protocols/xmpp'

require File.dirname(__FILE__) + '/examples/actors/herault'
require File.dirname(__FILE__) + '/examples/actors/randomz'
require File.dirname(__FILE__) + '/examples/actors/chained'
require File.dirname(__FILE__) + '/examples/actors/inner'
require File.dirname(__FILE__) + '/examples/delegates/debugger'

unless ENV["DEBUGGER"]
  Pelvis.logger.level = Logger::WARN
end
#Blather::LOG.level = Logger::DEBUG

EM.run do
  Pelvis.connect(:xmpp, :jid => "herault@localhost/agent", :password => "testing") do |agent|
    agent.actors << Herault
    puts "herault is ready"
  end

  Pelvis.connect(:xmpp, :jid => "dummy@localhost/agent", :password => "testing") do |agent|
    agent.actors << Randomz
    agent.actors << Chained
    puts "chained is ready"
  end

  #Pelvis.connect(:xmpp, :jid => "dummy2@localhost/agent", :password => "testing") do |agent|
    #agent.actors << Inner
    #puts "inner is ready"
  #end

  #Pelvis.connect(:xmpp, :jid => "admin@localhost/agent", :password => "testing") do |agent|
    #puts "bar is ready"
    #agent.request(:all, "/do/random", {}, :delegate => Debugger.new)
    #agent.request(:all, "/chained", {}, :delegate => Debugger.new)
  #end
end
